### ISSUE TITLE
Assembler gives invalid expression error

### ISSUE THREAD

**Issue by bobbarnes1981** [slu4coder/Minimal-64x4-Home-Computer#10]
I think there could be a bug in asm.exe

this code works

```
#org 0x2000
LDI 0x0b
```

but this code fails

```
#org 0x2000
LDI 0x0B
```
ERROR in line 2: Invalid expression.

**Comment by slu4coder** [comment]
I've just confirmed this. As you point out correctly, this is only an issue in the cross-assembler asm.exe, not in the native Minimal 64x4 version. Will look into this.

**Comment by slu4coder** [comment]
Thanks for pointing this out. I've found and fixed this bug and just re-uploaded asm.exe, asm.cpp and the emulator.
Cheers!
