### ISSUE TITLE
Emulator Keyboard Input for [{ and ;:

### ISSUE THREAD

**Issue by bobbarnes1981** [slu4coder/Minimal-64x4-Home-Computer#11]
I am experiencing strange behaviour with the emulator on Windows 11 with a UK keyboard.

The keys '{' '[' ';' and ':' don't appear to be working.

I used a fresh clone of the repo and the provided flash.bin.

It appears to have the same issue if I generate a new flash.bin from os.asm.

**Comment by bobbarnes1981** [comment]
No sorry, the keyboard layout works fine on the real hardware, but the emulator doesn't respond to those two keys.

**Comment by slu4coder** [comment]
I see, now I get it ;-). I suspect this might be related to German "Umlaut" keys on my keyboard being ignored by the emulator. I'll look into this.

**Comment by slu4coder** [comment]
I've added support for the missing keys now and re-uploaded the emulator .exe.
