### ISSUE TITLE
Keyboard issue

### ISSUE THREAD

**Issue by nateo87** [slu4coder/Minimal-64x4-Home-Computer#15]
Having some trouble with the keyboard; it continually outputs lower-case "v"s. Will update shortly with what I find on the scope.

For clarification, I'm using a compact Perixx PS/2 keyboard. I tried with a couple XT keyboards with a PS2 converter, but it just caused the computer to lock up.

**Comment by slu4coder** [comment]
Hi Nate,

I suspect you are using a modern PS/2 keyboard that insists on a handshake with the host system. You can verify this easily if you have a digital oscilloscope. If the keyboard send data without you pressing a key you can't use it with the Minimal.
I had the same issue, too, and basically hacked the PS/2 keyboard with an Arduino Nano to get around this. Can't recommend it. I'd suggest to buy an old 8$ PS/2 keyboard. Never had problems with those.

**Comment by nateo87** [comment]
Yeah, I initially bought it to be used with my RC2014. I'll see what I can do for cheap, I'll probably stop by around the local thrift stores and see what I can find. What I'd really like to do eventually is make a PS/2 keyboard or build an open source one so I can integrate it into a custom case. I would love to do something aesthetically in line with something like the Ohio Scientific Challenger series.

**Comment by nateo87** [comment]
Attached are photos of my scope checking out the clock and data lines. Sure looks like it's trying to do the handshake/initialization thing. Just curious, what was your workaroumd for this? All this work with keyboard signals is making me curious about how it all works. 
![20240524_171720](https://github.com/slu4coder/Minimal-64x4-Home-Computer/assets/79879072/ae560bd7-47cc-42e9-a842-37228f1571bd)
![20240524_171804](https://github.com/slu4coder/Minimal-64x4-Home-Computer/assets/79879072/ca57d3fc-5e74-4ff8-ae80-802ac0ce380b)

**Comment by slu4coder** [comment]
I remember, my workaround was a longer hack. I had ordered a modern mini PS/2 board that did show the exact same behavior as yours, i. e. sending 'v'. I tried it on an old 486 laptop and it worked just fine. I looked at the communication between laptrop and keyboard:
1) Host (laptop) receives some data ('v').
2) Host waits 1000µs, then pulls CLK line LOW for ~10µs, then releases CLK back to HIGH.
    This puts the keyboard in send mode.
3) Host receives keystrokes from PS/2 keyboard.
I've integrated an Arduino Nano into the case of the PS/2 keyboard as a relay between the keyboard and my computer. The Arduino did the above and after the communication starts, it only samples and relays the CLK and DAT lines.

`void setup()
{
  DDRC    = 0b00000000;   // A1-4: inputs
  PORTC   = 0b00011110;   // use pull-ups
  delayMicroseconds(100); // wait for the inputs to stabilize
  DDRC    = 0b00000110;   // A2: Nano CLK out, A1: Nano DAT out, A4: PS/2 CLK in (out), A3: PS/2 DAT in

  unsigned long t0, t1;
    
  do {                                     // wait CLK=HIGH for at least 1000µs
    t0 = micros(); t1 = t0;
    while((PINC & 0b00010000) != 0 && t1-t0 < 1000) t1 = micros();
  } while(t1-t0 < 1000);

  for(byte i=0; i<11; i++)                 // now read 11 bits (Start, 0-7, P, Stop)
  {
    while((PINC & 0b00010000) != 0);       // warte, solange CLK=HIGH
    while((PINC & 0b00010000) == 0);       // warte, solange CLK=LOW
  }

  // keyboard has released CLK, now the host pulls it low for at least 7µs to start communication
  delayMicroseconds(10);  // can be as late as 1200µs after CLK went finally HIGH
  DDRC    = 0b00010110;   // host takes control over CLK
  PORTC   = 0b00001110;   // host sets CLK=LOW
  delayMicroseconds(10);  // host waits >= 6µs
  PORTC   = 0b00011110;   // host sets CLK=HIGH
  DDRC    = 0b00000110;   // host sets CLK and DAT back to input

  do {                                     // wait CLK=HIGH for at least 1000µs
    t0 = micros(); t1 = t0;
    while((PINC & 0b00010000) != 0 && t1-t0 < 1000) t1 = micros();
  } while(t1-t0 < 1000);

  noInterrupts();                          // switch off all interrupts
}

void loop()
{
  byte a = (PINC & 0b00011000)>>2;
  PORTC = 0b00011000 | a; // permanently read A4 and A3, write the result to A2 and A1
}`

**Comment by nateo87** [comment]
Got an early 00's PS/2 keyboard from the thrift shop, and sure enough, it works perfectly. Thanks for posting your Arduino code, I might try it out for myself just for kicks.

**Comment by nateo87** [comment]
Keyboard issues documented and solved.
